// This file is auto-generated by @hey-api/openapi-ts

/**
 * BasePublicWithTables
 */
export type BasePublicWithTables = {
    /**
     * Id
     */
    id?: number | null;
    /**
     * Name
     */
    name: string;
    /**
     * Baseid
     */
    baseId: string;
    /**
     * Tables
     */
    tables: Array<Table>;
};

/**
 * Table
 */
export type Table = {
    /**
     * Id
     */
    id?: number | null;
    /**
     * Name
     */
    name: string;
    /**
     * Baseid
     */
    baseId?: number | null;
    /**
     * Tableid
     */
    tableId: string;
};

export type ReadBasesBasesGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/bases';
};

export type ReadBasesBasesGetResponses = {
    /**
     * Response Read Bases Bases Get
     * Successful Response
     */
    200: Array<BasePublicWithTables>;
};

export type ReadBasesBasesGetResponse = ReadBasesBasesGetResponses[keyof ReadBasesBasesGetResponses];

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};